AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable
  SuggestExtensions: false

Style/Documentation:
  # Skips checking to make sure top level modules / classes have a comment.
  Enabled: false

Layout/LineLength:
  Max: 100
  Exclude:
    - "**/*.gemspec"

Metrics/ModuleLength:
  Exclude:
    - "lib/pllum/http.rb"

Metrics/AbcSize:
  Max: 20

Metrics/PerceivedComplexity:
  Max: 20

Metrics/CyclomaticComplexity:
  Max: 20

Metrics/MethodLength:
  Max: 20

Metrics/ClassLength:
  Max: 120

Style/FrozenStringLiteralComment:
  Enabled: false

Gemspec/DevelopmentDependencies:
  Enabled: false

Metrics/ParameterLists:
  Max: 6